// Custom types for configuration API endpoints not generated by OpenAPI
import { StaffRegisterRequestRoleEnum, StaffRegisterRequestSystemLanguageEnum } from './api';

export interface RetrySwitchStatusDto {
    enabled: boolean;
}

export interface CustomStaffRegisterRequest {
    email: string;
    password: string;
    phone?: string;
    role: StaffRegisterRequestRoleEnum;
    name: string;
    surname: string;
    patronymic?: string;
    systemLanguage: StaffRegisterRequestSystemLanguageEnum;
}