/* tslint:disable */
/* eslint-disable */
/**
 * InRussianBackend API
 * API для проекта InRussian, которое используется для /домен вебсайта/ и приложения InRussian для Android и iOS.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

